
# Load libs
```{r message=FALSE, warning=FALSE}
library(Matrix, quietly = T)
library(dplyr, quietly = T)
library(Seurat, quietly = T)
library(SeuratDisk, quietly = T)

library(CellChat, quietly = T)
library(future, quietly = T)
library(cluster, quietly = T)
library(parallel, quietly = T)

library(ggplot2, quietly = T)
library(patchwork, quietly = T)
library(pals, quietly = T)
library(viridis, quietly = T)
library(data.table, quietly = T)
library(shades, quietly = T)

source("/home/dwm269/DWM_utils/sc_utils/seurat_helpers/seutils.R")
source("/home/dwm269/DWM_utils/sc_utils/seurat_helpers/seuplots.R")
source("/home/dwm269/DWM_utils/plotting_utils/scThemes.R")
# scTheme <- scThemes()
```

```{r}
meta <- read.csv("/workdir/dwm269/scCardiacOrganoid/resources/metadata.csv")
meta <- meta[meta$include,]
meta
```

Load CellChat object
```{r}
load(
  file="/workdir/dwm269/scCardiacOrganoid/data/robjs/scCO_v7-1_cellchat.RData"
)
```

## Global plotting
```{r}
groupSize <- as.numeric(table(scco.chat@idents))
par(mfrow = c(1,2), xpd=TRUE)
netVisual_circle(
  scco.chat@net$count, 
  vertex.weight = groupSize, 
  weight.scale = T,
  label.edge= F, 
  title.name = "Number of interactions"
  )

netVisual_circle(
  scco.chat@net$weight, 
  vertex.weight = groupSize, 
  weight.scale = T, 
  label.edge= F, 
  title.name = "Interaction weights/strength"
  )
```


```{r}
# Heatmap
par(mfrow = c(1,1), xpd=TRUE)
netVisual_heatmap(
  scco.chat,
  slot.name="netP",
  measure="weight",
  # color.use = celltype.colors[sort(c(sources.use,targets.use))],
  # sources.use = sources.use,
  # targets.use = targets.use,
  # cluster.rows=T, cluster.cols=T,
  # color.heatmap = "YlOrRd",
  font.size.title = 16,
  font.size = 14,
  width=6,
  height=22
)
```


## Focused plotting
### Chord plot: endo -> meso
```{r}

sources.use = c(
  "Definitive_Endoderm",
  # "Gut Mesenchyme",
  "Foregut_Epithelium"
  # "Liver Progenitors"
)
targets.use = c(
  "Cardiac_Mesoderm",
  "Fibroblasts",
  "Smooth_Muscle",
  "Endocardial",
  "Epicardial",
  # "Cardiomyocytes (early)",
  "Cardiomyocytes"
)

# par(mfrow = c(1,1), xpd=TRUE)
# netVisual_chord_gene(
#   scco.chat, 
#   sources.use = sources.use,
#   targets.use = targets.use,
#   slot.name = "netP",
#   thresh=10^-150,
#   small.gap=0.25,
#   big.gap=5,
#   title.name = "Endo -> Meso",
#   # color.use = pals::polychrome()[3:36] %>% unlist(),
#   show.legend = T, 
#   legend.pos.x = 0, legend.pos.y = 100,
#   # annotationTrackHeight=0.5,
#   lab.cex=1
#   # width=width,
#   # height=height
# )
```


```{r}
netVisual_bubble(
  scco.chat, 
  sources.use = sources.use, 
  targets.use = targets.use,
  # thresh = 10^-150,
  # max.dataset = 15,
  min.quantile = c(0.5),
  signaling = c("FN1","MK","CDH","LAMININ","PARs"),
  remove.isolate = FALSE
)
```

### Chord plot: meso -> endo
```{r}
sources.use = c(
  "Cardiac Mesoderm",
  "Fibroblasts",
  "Smooth Muscle",
  "Endocardial",
  "Epicardial",
  "Cardiomyocytes (early)",
  "Cardiomyocytes (late)"
)
targets.use = c(
  "Definitive Endoderm",
  "Gut Mesenchyme",
  "Foregut Epithelium"
  # "Liver Progenitors"
)

par(mfrow = c(1,1), xpd=TRUE)
netVisual_chord_gene(
  scco.chat, 
  sources.use = sources.use,
  targets.use = targets.use,
  slot.name = "netP",
  thresh=10^-150,
  # small.gap=0.25,
  # big.gap=5,
  # color.use = pals::polychrome()[3:36] %>% unlist(),
  show.legend = T, 
  legend.pos.x = 0, legend.pos.y = 100,
  lab.cex=1
  # width=width,
  # height=height
)
```


```{r}
sources.use = c(
  # "Cardiac Mesoderm",
  # "Fibroblasts",
  # "Smooth Muscle",
  "Endocardial",
  "Epicardial",
  # "Cardiomyocytes (early)",
  # "Cardiomyocytes (late)"
  "Definitive Endoderm",
  "Gut Mesenchyme",
  "Foregut Epithelium"
)
targets.use = c(
  # "Definitive Endoderm",
  # "Gut Mesenchyme",
  # "Foregut Epithelium"
  "Cardiomyocytes (early)",
  "Cardiomyocytes (late)"
  # "Liver Progenitors"
)
netVisual_bubble(
  scco.chat,
  sources.use = sources.use, 
  targets.use = targets.use,
  thresh = 10^-150,
  # signaling = c("MK","CDH","BMP","NCAM","CADM"),
  signaling = c("VEGF","NRG"),
  min.quantile = c(0.5),
  remove.isolate = FALSE
)
```


##########################
#  Time-series analysis  #
##########################
```{r}
# https://htmlpreview.github.io/?https://github.com/sqjin/CellChat/blob/master/tutorial/Comparison_analysis_of_multiple_datasets.html
seu.list <- SplitObject(
  scco.seu,
  split.by = "sample"
)
```

Run CellChat on each sample individually
```{r}
cellchat.list <- lapply(
  seu.list,
  FUN = function(SEU){
    tmp.cellchat <- createCellChat(
      object = GetAssayData(
        SEU,
        assay = "RNA",
        slot = "data"
      ),
      meta = data.frame(
        leiden_harmony_types = droplevels(SEU$leiden_harmony_types),
        row.names = Cells(SEU)
      ),
      group.by = "leiden_harmony_types"
    )
    print("Made tmp CellChat object...")
    # Set the database to use (whole CellChat database)
    tmp.cellchat@DB <- CellChatDB.human
    
    # subset the expression data of signaling genes for saving computation cost
    tmp.cellchat <- subsetData(tmp.cellchat)
    
    # CellChat processing (memory intensive for large datasets)
    tmp.cellchat <- identifyOverExpressedGenes(tmp.cellchat)
    tmp.cellchat <- identifyOverExpressedInteractions(tmp.cellchat)
    gc()
    
    
    # project gene expression data onto PPI network (optional)
    tmp.cellchat <- projectData(tmp.cellchat, PPI.human)
    
    # tmp.cellchat@idents = droplevels(tmp.cellchat@idents, exclude = setdiff(levels(meta$labels),unique(meta$labels)))
    
    
    tmp.cellchat <- computeCommunProb(tmp.cellchat)
    
    # Filter out the cell-cell communication if there are only few number of cells in certain cell groups
    tmp.cellchat <- filterCommunication(tmp.cellchat, min.cells = 10)
    
    tmp.cellchat <- computeCommunProbPathway(tmp.cellchat)
    
    tmp.cellchat <- aggregateNet(tmp.cellchat)
    
    # Compute the network centrality scores
    tmp.cellchat <- netAnalysis_computeCentrality(
      tmp.cellchat, 
      slot.name = "netP"
    ) # the slot 'netP' means the inferred intercellular communication network of signaling pathways
    
    return(tmp.cellchat)
  }
)


```

```{r}
save(cellchat.list, file="/workdir/dwm269/scCardiacOrganoid/robjs/cellchat_list_v1.RData")
```

# Comparative analysis on the 600um samples
```{r}
merged.cellchat <- mergeCellChat(
  cellchat.list[meta$patterm=="600um"], 
  add.names = meta$sample[meta$patterm=="600um"]
)
```



```{r}

```
