
# Session set-up
## Libs, setwd
```{r setup}
knitr::opts_knit$set(root.dir = '/workdir/dwm269/scCardiacOrganoid/')
```

```{r message=FALSE, warning=FALSE}
# analysis
library(Matrix, quietly = T)
library(dplyr, quietly = T)
library(Seurat, quietly = T)
library(future, quietly = T)
# library(cluster)
library(parallel, quietly = T)
library(data.table, quietly = T)

# plotting
library(ggplot2, quietly = T)
library(patchwork, quietly = T)
library(pals, quietly = T)
library(viridis, quietly = T)
library(shades, quietly = T)

# DWMutils
source("~/DWM_utils/sc_utils/seurat_helpers/seutils.R")
source("~/DWM_utils/sc_utils/seurat_helpers/seuplots.R")

```

## Figure settings
```{r}
small.font = 6*2
big.font = 8*2
line.width = 0.5
pt.size=0.01
pt.stroke=0.3
label.size=2

source("~/DWM_utils/plotting_utils/scThemes.R")
scTheme <- scThemes(
  small.font = small.font,
  big.font = big.font,
  line.width = line.width,
  pt.size=pt.size,
  pt.stroke=pt.stroke,
  label.size=label.size
)
```
## Color palettes
```{r}
mckolors <- read.csv("~/DWM_utils/plotting_utils/McKolors_v1.csv") %>% 
  as.list() %>%
  lapply(
    FUN=function(X) X[X!=""]
  )
```

## Color palette for cell types
```{r}



```


## Load data
```{r}
if(!exists("scco.seu")){
  scco.seu <- readRDS("data/robjs/scCO_v7-4.rds")
}

scco.seu$sample<-factor(
  scco.seu$sample,
  levels=sort(unique(scco.seu$sample))
)
```

Order cell types...
```{r}
scco.seu$cell_types_levl2 <- factor(
  scco.seu$cell_types_levl2,
  levels=c(
    "iPSCs","Primitive_Streak", 
    "Definitive_Endoderm", "Foregut_Epithelium", "Liver_Progenitors",# Endoderm
    "Cardiac_Mesoderm","Fibroblasts","Smooth_Muscle","Endocardial","Epicardial","Cardiomyocytes", # Mesoderm/cardiac
    "Non-neural_Ectoderm"
  )
)
```


## Plots!
```{r}
ggplot(
    scco.seu@meta.data,
    aes(
        x=doublet_score,
        fill=pattern
    )
)+
    geom_histogram(
        bins=100
        # alpha=0.5
    )+
    scTheme$bar+
    theme(
        legend.position="right",
        axis.text.y = element_text(angle=0),
        strip.text = element_text(face="bold")
    )+scale_y_log10()+
    facet_wrap(
        facets="sample"
    )+labs(fill="Spot Size")
```


# Cell type plots
## Cell types across differentiation
```{r fig.height=6, fig.width=10}
stacked.celltype.600um <- ggplot(
  # scco.seu@meta.data,
  scco.seu@meta.data[scco.seu$pattern=="600um",],
  aes(
    x=timepoint,
    fill=cell_types
  )
) +
  geom_bar(
    color="black",
    width = 0.5,
    position="fill"
  ) +
  facet_wrap(facets="pattern",ncol = 1)+
  scTheme$bar +
  theme(
    legend.position = "right",
    legend.title=element_blank(),
    legend.text = element_text(size = small.font),
    axis.text.x = element_text(size = small.font),
    axis.text.y = element_text(size = small.font,angle=0,hjust=1),
    axis.title = element_blank(),
    strip.text = element_text(size = small.font,face="bold")
  ) +
  scale_y_continuous(labels=scales::percent)+
  scale_fill_manual(
    values=mckolors$polychrome#[c(3:16)]
    # values=mckolors$rickandmorty_ggsci
  )
stacked.celltype.600um
ggsave(
  filename = "figures/manuscript_figs/stacked_celltype_v2.pdf",
  device = "pdf",
  width = 17.4, #17.4cm max width
  height= 10,
  units = "cm",
  dpi = 400
)
```
PHATE, split.by spot size
```{r}
time_int=21
subset(
  scco.seu,
  cells = sample(Cells(scco.seu)[scco.seu$time_int%in%c(time_int)])
) %>% DimPlot(
  # scco.seu,
  reduction="phate_harmony_sp",
  split.by="pattern",
  group.by = "cell_types",
  # cells = Cells(scco.seu)[scco.seu$timepoint=='D4'],
  cols = mckolors$polychrome,
  raster=F
) +
  # facet_grid(
  #   rows=vars(timepoint),
  #   cols=vars(pattern)
  # )+
  scTheme$umap +
  theme(
    plot.title=element_blank(),
    legend.title=element_blank(),
    legend.text = element_text(size = 12),
    legend.position = "bottom",legend.justification = 'center',
    axis.title = element_blank(),
    axis.line=element_blank(),
    strip.text = element_text(size = 12,face="bold")
  )+
  coord_fixed()
```

PHATE, split.by timepoint
```{r}
subset(
  scco.seu,
  cells = sample(Cells(scco.seu)[scco.seu$pattern=="600um"])
) %>% DimPlot(
  # scco.seu,
  reduction="phate_harmony_sp",
  split.by="timepoint",
  # cells = sample(Cells(scco.seu)[scco.seu$pattern=="600um"]),
  group.by = "cell_types",
  cols = alpha(mckolors$polychrome, 0.7),
  raster=F
) +
  scTheme$umap +
  theme(
    plot.title=element_blank(),
    legend.title=element_blank(),
    legend.text = element_text(size = 12),
    legend.position = "bottom",legend.justification = 'center',
    axis.title = element_blank(),
    axis.line=element_blank(),
    strip.text = element_text(size = 12,face="bold")
  )+
  coord_fixed()

```

PHATE, split.by spot size & timepoint
```{r}
DimPlot(
  scco.seu,
  reduction="phate_harmony_sp",
  # split.by=c("pattern","timepoint"),
  group.by = "leiden_harmony_sp_1.0", #cell_types
  # ncol = 4,
  # order = sample(Cells(scco.seu)),
  label = T,label.box = T,
  pt.size = 0.5,
  cols = alpha(mckolors$polychrome, 0.2),
  raster=F
) +
  scTheme$umap +
  theme(
    plot.title=element_blank(),
    legend.title=element_blank(),
    legend.text = element_text(size = 12),
    axis.title = element_blank(),
    axis.line=element_blank(),
    strip.text = element_text(size = 12,face="bold")
  )+
    guides(color = guide_legend(override.aes = list(alpha = 1,size=4)))+
  coord_fixed()

```


```{r}
group.by=c("time_int","phase","pattern","cell_types_level2")
cols=list(
  viridis(length(unique(scco.seu$time_int))),
  mckolors$primary,
  mckolors$primary,
  mckolors$polychrome
)
plot.list <- list()

for(i in 1:length(group.by)){
  plot.list[[i]]<-DimPlot(
    scco.seu,
    reduction="phate_harmony_sp",
    cells=sample(Cells(scco.seu)[scco.seu$pattern_int==600]),
    group.by = group.by[i],
    # ncol = 4,
    # order = sample(Cells(scco.seu)),
    cols = alpha(cols[[i]], 0.4),
    raster=F
  ) +
    scTheme$umap +
    theme(
      plot.margin = unit(rep(0,4),"cm"),
      plot.title=element_blank(),
      # legend.title=element_blank(),
      legend.text = element_text(size = small.font),
      axis.title = element_blank(),
      axis.line=element_blank(),
      strip.text = element_text(size = small.font,face="bold")
    )+
    labs(
      color= group.by[i]
    )+
    guides(color = guide_legend(override.aes = list(alpha = 1,size=4)))+
    coord_fixed()
}

plot.list[[3]]<-FeaturePlot(
  scco.seu,
  reduction="phate_harmony_sp",
  cells=sample(Cells(scco.seu)[scco.seu$pattern_int==600]),
  features  = "dpt_pseudotime",
  # ncol = 4,
  # order = sample(Cells(scco.seu)),
  cols = rev(mckolors$spectral),
  raster=F
) +
  scTheme$umap +
  xlim(range(scco.seu@reductions$X_phate@cell.embeddings[,1]))+
  ylim(range(scco.seu@reductions$X_phate@cell.embeddings[,2]))+
  labs(
    fill="dpt_pseudotime"
  )+
  theme(
    plot.margin = unit(rep(0,4),"cm"),
    plot.title=element_blank(),
    legend.title=element_blank(),
    legend.text = element_text(size = small.font),
    axis.title = element_blank(),
    axis.line=element_blank(),
    strip.text = element_text(size = small.font,face="bold")
  )+
  # guides(color = guide_legend(override.aes = list(alpha = 1,size=4)))+
  coord_fixed()

wrap_plots(
  plot.list,
  nrow=2
)
```


# Build & save Fig 1
```{r fig.height=10, fig.width=14.5}
wrap_plots(
  stacked.celltype.600um,
  wrap_plots(
    plot.list,
    nrow=2
  ),
  heights = c(1, 4)
)
```

